# TO: kj_base_it
FROM kowaraj/test:kj_base

# it
RUN yum install -y net-tools
RUN yum install -y tcpdump
RUN yum install -y iproute
RUN yum install -y lsof


# Run app.py when the container launches
CMD "bash"
